use arboard::Clipboard;
use clap::Parser;
use std::env;
use std::fs;
use std::io::{self, Read, Write};
use std::process::{Command, Stdio};
use the_clipboard_centaur::{apply_block, parse_blocks, ApplyResult};

#[derive(Parser, Debug)]
#[command(
    name = "The Clipboard Centaur",
    version,
    about = "Applies LLM-generated search/replace blocks directly to local files.",
    long_about = "A fast, deterministic, and consumer-friendly CLI that parses search/replace blocks (e.g. from ChatGPT) and applies them locally with deep safety nets."
)]
struct Args {
    /// Read the patch text directly from the OS clipboard instead of standard input.
    #[arg(short, long)]
    clipboard: bool,

    /// Read the patch text from a specific file instead of standard input.
    #[arg(short, long)]
    file: Option<String>,

    /// Fallback to a local LLM via Ollama if the deterministic patch fails (e.g. 'llama3' or 'deepseek-coder')
    #[arg(short, long)]
    llm: Option<String>,
}

fn apply_with_llm(model: &str, file_path_str: &str, search: &str, replace: &str) -> bool {
    let file_path = std::path::Path::new(file_path_str);
    let content = fs::read_to_string(file_path).unwrap_or_default();
    
    let prompt = format!(
        "You are a local file-writing agent. I will provide you with a series of Search/Replace diffs generated by a master AI model, followed by the contents of my local file. Your sole job is to execute the diffs and output the final, complete updated file. Do not chat or explain anything.\n\nThe Diffs:\n<<<<<<< SEARCH\n{}\n=======\n{}\n>>>>>>> REPLACE\n\nCurrent File Content:\n{}\n\nOutput the completely updated file now:",
        search, replace, content
    );

    println!("🤖 Asking Ollama ({}) to resolve the patch for {}...", model, file_path_str);
    
    let mut child = match Command::new("ollama")
        .arg("run")
        .arg(model)
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .spawn()
    {
        Ok(c) => c,
        Err(e) => {
            println!("❌ ERROR: Failed to execute Ollama. Make sure it is installed and in your PATH. ({})", e);
            return false;
        }
    };
        
    if let Some(mut stdin) = child.stdin.take() {
        if let Err(e) = stdin.write_all(prompt.as_bytes()) {
            println!("❌ ERROR writing to Ollama stdin: {}", e);
            return false;
        }
    }
    
    match child.wait_with_output() {
        Ok(out) => {
            if out.status.success() {
                let mut result_text = String::from_utf8_lossy(&out.stdout).to_string();
                
                // Strip markdown code fences if the LLM wrapped it
                if result_text.starts_with("```") {
                    let mut lines: Vec<&str> = result_text.lines().collect();
                    if !lines.is_empty() && lines[0].starts_with("```") {
                        lines.remove(0);
                    }
                    if !lines.is_empty() && lines.last().unwrap().starts_with("```") {
                        lines.pop();
                    }
                    result_text = lines.join("\n");
                }
                
                if let Err(e) = fs::write(file_path, result_text) {
                    println!("❌ ERROR writing LLM output to {}: {}", file_path_str, e);
                    false
                } else {
                    println!("✅ Successfully updated via Local LLM: {}", file_path_str);
                    true
                }
            } else {
                println!("❌ ERROR: Ollama failed: {}", String::from_utf8_lossy(&out.stderr));
                false
            }
        },
        Err(e) => {
            println!("❌ ERROR: Failed to read Ollama stdout: {}", e);
            false
        }
    }
}

fn main() {
    let args = Args::parse();

    let input = if args.clipboard {
        println!("Reading patch instructions from the clipboard...");
        match Clipboard::new() {
            Ok(mut cb) => match cb.get_text() {
                Ok(text) => text,
                Err(e) => {
                    eprintln!("Failed to read text from clipboard: {}", e);
                    return;
                }
            },
            Err(e) => {
                eprintln!("Failed to initialize clipboard: {}", e);
                return;
            }
        }
    } else if let Some(path) = args.file {
        println!("Reading patch instructions from {}...", path);
        match fs::read_to_string(&path) {
            Ok(text) => text,
            Err(e) => {
                eprintln!("Failed to read file {}: {}", path, e);
                return;
            }
        }
    } else {
        println!("Paste the output from ChatGPT below, then press Ctrl+D (Unix) or Ctrl+Z then Enter (Windows) to execute:\n");
        let mut text = String::new();
        if let Err(e) = io::stdin().read_to_string(&mut text) {
            eprintln!("Failed to read from stdin: {}", e);
            return;
        }
        text
    };

    let blocks = parse_blocks(&input);
    if blocks.is_empty() {
        println!("No valid Search/Replace blocks found in the input.");
        return;
    }

    let current_dir = env::current_dir().unwrap_or_else(|_| std::path::PathBuf::from("."));

    for block in blocks {
        match apply_block(&current_dir, &block) {
            ApplyResult::Created(path) => println!("✅ Created new file: {}", path),
            ApplyResult::Updated(path) => println!("✅ Successfully updated: {}", path),
            ApplyResult::AmbiguousMatch(path) => {
                println!("❌ ERROR: Search block matches multiple locations in {}. Please be more specific.", path);
                if let Some(ref model) = args.llm {
                    apply_with_llm(model, &path, &block.search, &block.replace);
                }
            }
            ApplyResult::MatchNotFound(path) => {
                println!("❌ ERROR: Could not find exact match for SEARCH block in {}", path);
                if let Some(ref model) = args.llm {
                    apply_with_llm(model, &path, &block.search, &block.replace);
                }
            }
            ApplyResult::IoError(path, err) => {
                println!("❌ ERROR: IO Error for file {}: {}", path, err)
            }
            ApplyResult::SecurityError(err) => {
                println!("🚫 ERROR: Security violation: {}", err)
            }
        }
    }
}
