use arboard::Clipboard;
use clap::Parser;
use std::env;
use std::fs;
use std::io::{self, Read, Write};
use std::process::{Command, Stdio};
use sysinfo::System;
use the_clipboard_centaur::{apply_block, parse_blocks, ApplyResult};

#[derive(Parser, Debug)]
#[command(
    name = "The Clipboard Centaur",
    version,
    about = "Applies LLM-generated search/replace blocks directly to local files.",
    long_about = "A fast, deterministic, and consumer-friendly CLI that parses search/replace blocks (e.g. from ChatGPT) and applies them locally with deep safety nets."
)]
struct Args {
    /// Read the patch text directly from the OS clipboard instead of standard input.
    #[arg(short, long)]
    clipboard: bool,

    /// Read the patch text from a specific file instead of standard input.
    #[arg(short, long)]
    file: Option<String>,

    /// Fallback to a local LLM via Ollama if the deterministic patch fails. Use 'auto' to automatically select the best model based on your system RAM.
    #[arg(short, long)]
    llm: Option<String>,

    /// Export files/directories into a single string (respecting .gitignore) and copy it to your clipboard for ChatGPT.
    #[arg(short, long, num_args = 0..)]
    export: Option<Vec<String>>,

    /// Run initial setup: verifies your environment, analyzes your RAM, and pre-downloads the optimal AI model.
    #[arg(long)]
    setup: bool,

    /// Bypass the safety size and chunk limits for massive exports
    #[arg(long)]
    force: bool,

    /// Specify a custom chunk size in characters for the exports (default: 300000)
    #[arg(long, default_value_t = 300_000)]
    chunk_size: usize,
}

fn resolve_auto_llm() -> String {
// ... (rest of resolve_auto_llm remains unchanged) ...
    let mut sys = System::new_all();
    sys.refresh_all();
    // memory is in bytes
    let total_ram_gb = sys.total_memory() as f64 / 1_073_741_824.0;
    let available_ram_gb = sys.available_memory() as f64 / 1_073_741_824.0;
    
    println!("🔍 Analyzing system specs: {:.1} GB Total RAM ({:.1} GB Available right now)", total_ram_gb, available_ram_gb);
    
    let (model, size, reason) = if available_ram_gb >= 20.0 {
        ("deepseek-coder:33b", "~19GB", "Massive available RAM. DeepSeek provides near GPT-4 level coding capabilities.")
    } else if available_ram_gb >= 6.0 {
        ("qwen2.5-coder:7b", "~4.5GB", "Great balance of intelligence and performance for your current available memory.")
    } else {
        ("qwen2.5-coder:1.5b", "~1GB", "Low available memory detected (e.g. from browser/IDE overhead). Ultra-lightweight model chosen to avoid crashing or swapping.")
    };
    
    println!("💡 Auto-Recommendation: Using '{}' (Download: {}) - {}", model, size, reason);
    model.to_string()
}

fn apply_with_llm(model: &str, file_path_str: &str, search: &str, replace: &str) -> bool {
// ... (rest of apply_with_llm remains unchanged) ...
    let file_path = std::path::Path::new(file_path_str);
    let content = fs::read_to_string(file_path).unwrap_or_default();
    
    let prompt = format!(
        "You are a local file-writing agent. I will provide you with a series of Search/Replace diffs generated by a master AI model, followed by the contents of my local file. Your sole job is to execute the diffs and output the final, complete updated file. Do not chat or explain anything.\n\nThe Diffs:\n<<<<<<< SEARCH\n{}\n=======\n{}\n>>>>>>> REPLACE\n\nCurrent File Content:\n{}\n\nOutput the completely updated file now:",
        search, replace, content
    );

    println!("🤖 Asking Ollama ({}) to resolve the patch for {}...", model, file_path_str);
    
    let mut child = match Command::new("ollama")
        .arg("run")
        .arg(model)
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .spawn()
    {
        Ok(c) => c,
        Err(e) => {
            println!("❌ ERROR: Failed to execute Ollama. Make sure it is installed and in your PATH. ({})", e);
            return false;
        }
    };
        
    if let Some(mut stdin) = child.stdin.take() {
        if let Err(e) = stdin.write_all(prompt.as_bytes()) {
            println!("❌ ERROR writing to Ollama stdin: {}", e);
            return false;
        }
    }
    
    match child.wait_with_output() {
        Ok(out) => {
            if out.status.success() {
                let mut result_text = String::from_utf8_lossy(&out.stdout).to_string();
                
                // Strip markdown code fences if the LLM wrapped it
                if result_text.starts_with("```") {
                    let mut lines: Vec<&str> = result_text.lines().collect();
                    if !lines.is_empty() && lines[0].starts_with("```") {
                        lines.remove(0);
                    }
                    if !lines.is_empty() && lines.last().unwrap().starts_with("```") {
                        lines.pop();
                    }
                    result_text = lines.join("\n");
                }
                
                if let Err(e) = fs::write(file_path, result_text) {
                    println!("❌ ERROR writing LLM output to {}: {}", file_path_str, e);
                    false
                } else {
                    println!("✅ Successfully updated via Local LLM: {}", file_path_str);
                    true
                }
            } else {
                println!("❌ ERROR: Ollama failed: {}", String::from_utf8_lossy(&out.stderr));
                false
            }
        },
        Err(e) => {
            println!("❌ ERROR: Failed to read Ollama stdout: {}", e);
            false
        }
    }
}

fn main() {
    let args = Args::parse();

    if args.setup {
        println!("\n🔧 Running The Clipboard Centaur Setup...\n");
        
        println!("==================================================");
        println!("🧠 HOW CENTAUR WORKS");
        println!("==================================================");
        println!("1. FAST PATH: You copy ChatGPT's code diffs to your clipboard.");
        println!("   Centaur runs a lightning-fast, deterministic regex patch to update your local files instantly.");
        println!("2. FALLBACK PATH: If ChatGPT hallucinates context and the patch fails, Centaur automatically");
        println!("   spins up an offline, local LLM to intelligently resolve the merge conflict.");
        println!("3. PERFORMANCE: Ollama automatically utilizes KV Caching, keeping the fallback model hot in ");
        println!("   your VRAM for 5 minutes so consecutive edits happen instantly without reload penalties.");
        println!("==================================================\n");

        println!("Checking for Ollama installation...");
        let ollama_check = Command::new("ollama").arg("--version").output();
        match ollama_check {
            Ok(out) if out.status.success() => println!("✅ Ollama is installed: {}", String::from_utf8_lossy(&out.stdout).trim()),
            _ => {
                println!("❌ Ollama is NOT installed or not found in PATH.");
                println!("Please download and install it from https://ollama.com, then run this setup again.");
                return;
            }
        }
        
        println!("\nAnalyzing system hardware to determine the best local AI model for diff resolution...");
        let model = resolve_auto_llm();
        
        println!("\n📥 Pre-downloading model '{}' so it's ready instantly when a diff fails...", model);
        println!("(This may take a few minutes depending on your internet connection)");
        
        let mut child = Command::new("ollama")
            .arg("pull")
            .arg(&model)
            .spawn()
            .expect("Failed to start ollama pull");
            
        let status = child.wait().expect("Failed to wait on ollama pull");
        if status.success() {
            println!("\n✅ Setup complete! The AI model is cached locally.");
            println!("You are now ready to seamlessly use: centaur -c --llm auto");
        } else {
            println!("\n❌ Failed to pull the model. Please check your internet connection and try again.");
        }
        return;
    }

    if let Some(mut paths) = args.export {
        if paths.is_empty() {
            paths.push(".".to_string());
        }
        println!("📦 Exporting {} targets...", paths.len());
        
        let mut files_to_pack = Vec::new();
        for path_str in paths {
            let walker = ignore::WalkBuilder::new(&path_str).build();
            for result in walker {
                match result {
                    Ok(entry) => {
                        let p = entry.path();
                        if p.is_file() {
                            let path_str = p.to_string_lossy();
                            let file_name = p.file_name().unwrap_or_default().to_string_lossy();
                            if path_str.contains(".centaur_export") || file_name.starts_with("centaur_context_part") {
                                continue; // Never pack our own generated context chunks
                            }
                            
                            // Automatically skip massive files (like CSVs, DuckDB, SQLite) that user forgot to gitignore
                            if !args.force {
                                if let Ok(metadata) = p.metadata() {
                                    if metadata.len() > 1_000_000 {
                                        eprintln!("⚠️ Skipping massive file (>1MB): {}", file_name);
                                        continue;
                                    }
                                }
                            }
                            
                            files_to_pack.push(p.to_path_buf());
                        }
                    }
                    Err(err) => eprintln!("⚠️ Warning: Error walking directory: {}", err),
                }
            }
        }

        let chunks = the_clipboard_centaur::pack_files(files_to_pack, args.chunk_size);
        let total_chunks = chunks.len();

        if total_chunks == 0 {
            println!("No readable text files found to export.");
            return;
        }

        // Safety Guard 1: Absolute payload size (prevents single massive files like 2MB CSVs from bypassing chunk limits)
        let total_chars: usize = chunks.iter().map(|c| c.len()).sum();
        if !args.force && total_chars > 3_000_000 {
            println!("\n❌ ERROR: Project is too massive! Total payload is {} characters (Max: 3,000,000).", total_chars);
            println!("ChatGPT and Claude have hard context limits and cannot process a codebase this large.");
            println!("You are likely including massive datasets, compiled binaries, or dependencies.");
            println!("\nHow to fix:");
            println!("1. Ensure you have a .gitignore file (ignoring things like node_modules, target, venv).");
            println!("2. Explicitly target specific folders instead of the whole project:");
            println!("   Example: centaur --export src/ config.toml");
            println!("3. Bypass this safety limit with --force (e.g., centaur -e --force)");
            return;
        }

        // Safety Guard 2: Chunk count (prevents generating too many files for the UI drag-and-drop)
        if !args.force && total_chunks > 15 {
            println!("\n❌ ERROR: Project is too massive! Generated {} context files.", total_chunks);
            println!("ChatGPT and Claude have hard context limits and cannot process a codebase this large.");
            println!("You are likely including build directories, datasets, or dependencies.");
            println!("\nHow to fix:");
            println!("1. Ensure you have a .gitignore file (ignoring things like node_modules, target, venv).");
            println!("2. Explicitly target specific folders instead of the whole project:");
            println!("   Example: centaur --export src/ config.toml");
            println!("3. Bypass this safety limit with --force (e.g., centaur -e --force)");
            return;
        }

        if total_chunks == 1 {
            match Clipboard::new() {
                Ok(mut cb) => {
                    if let Err(e) = cb.set_text(chunks[0].clone()) {
                        eprintln!("❌ Failed to write to clipboard: {}", e);
                    } else {
                        println!("✅ Successfully packed all files into your clipboard! Ready to paste into ChatGPT.");
                    }
                },
                Err(e) => eprintln!("❌ Failed to initialize clipboard: {}", e),
            }
        } else {
            println!("\n📦 EXPORT COMPLETE - LARGE PROJECT DETECTED");
            println!("Project split into {} files for easy uploading.", total_chunks);
            println!("--------------------------------------------------");
            
            let export_dir = std::env::temp_dir().join("centaur_export");
            if export_dir.exists() {
                let _ = fs::remove_dir_all(&export_dir); // Clear old exports
            }
            if let Err(e) = fs::create_dir_all(&export_dir) {
                eprintln!("❌ Failed to create temporary export directory: {}", e);
                return;
            }

            for (i, chunk) in chunks.iter().enumerate() {
                let file_path = export_dir.join(format!("centaur_context_part{}.txt", i + 1));
                if let Err(e) = fs::write(&file_path, chunk) {
                    eprintln!("❌ Failed to write {}: {}", file_path.display(), e);
                }
            }
            
            println!("✅ Saved {} context files into your system's temporary directory.", total_chunks);
            println!("Instead of pasting, simply drag and drop these files simultaneously into your ChatGPT/Claude chat window:");
            for i in 1..=total_chunks {
                println!("  - centaur_context_part{}.txt", i);
            }
            println!("--------------------------------------------------");
            
            // Auto-open file explorer to the temp directory
            #[cfg(target_os = "windows")]
            let _ = Command::new("explorer").arg(&export_dir).spawn();
            #[cfg(target_os = "macos")]
            let _ = Command::new("open").arg(&export_dir).spawn();
            #[cfg(target_os = "linux")]
            let _ = Command::new("xdg-open").arg(&export_dir).spawn();
        }
        return;
    }

    let input = if args.clipboard {
        println!("Reading patch instructions from the clipboard...");
        match Clipboard::new() {
            Ok(mut cb) => match cb.get_text() {
                Ok(text) => text,
                Err(e) => {
                    eprintln!("Failed to read text from clipboard: {}", e);
                    return;
                }
            },
            Err(e) => {
                eprintln!("Failed to initialize clipboard: {}", e);
                return;
            }
        }
    } else if let Some(path) = args.file {
        println!("Reading patch instructions from {}...", path);
        match fs::read_to_string(&path) {
            Ok(text) => text,
            Err(e) => {
                eprintln!("Failed to read file {}: {}", path, e);
                return;
            }
        }
    } else {
        println!("Paste the output from ChatGPT below, then press Ctrl+D (Unix) or Ctrl+Z then Enter (Windows) to execute:\n");
        let mut text = String::new();
        if let Err(e) = io::stdin().read_to_string(&mut text) {
            eprintln!("Failed to read from stdin: {}", e);
            return;
        }
        text
    };

    let blocks = parse_blocks(&input);
    if blocks.is_empty() {
        println!("No valid Search/Replace blocks found in the input.");
        return;
    }

    let resolved_llm = args.llm.map(|model| {
        if model.eq_ignore_ascii_case("auto") {
            resolve_auto_llm()
        } else {
            model
        }
    });

    let current_dir = env::current_dir().unwrap_or_else(|_| std::path::PathBuf::from("."));

    for block in blocks {
        match apply_block(&current_dir, &block) {
            ApplyResult::Created(path) => println!("✅ Created new file: {}", path),
            ApplyResult::Updated(path) => println!("✅ Successfully updated: {}", path),
            ApplyResult::AmbiguousMatch(path) => {
                println!("❌ ERROR: Search block matches multiple locations in {}. Please be more specific.", path);
                if let Some(ref model) = resolved_llm {
                    apply_with_llm(model, &path, &block.search, &block.replace);
                }
            }
            ApplyResult::MatchNotFound(path) => {
                println!("❌ ERROR: Could not find exact match for SEARCH block in {}", path);
                if let Some(ref model) = resolved_llm {
                    apply_with_llm(model, &path, &block.search, &block.replace);
                }
            }
            ApplyResult::IoError(path, err) => {
                println!("❌ ERROR: IO Error for file {}: {}", path, err)
            }
            ApplyResult::SecurityError(err) => {
                println!("🚫 ERROR: Security violation: {}", err)
            }
        }
    }
}
